import type { Action, ChatMessage, Language, ProgramCard as ProgramCardType } from "./types";
const currency = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });
function renderInline(text: string) { return text.split(/(\*\*[^*]+\*\*|_[^_]+_)/g).filter(Boolean).map((part, index) => part.startsWith("**") && part.endsWith("**") ? <strong key={index}>{part.slice(2, -2)}</strong> : part.startsWith("_") && part.endsWith("_") ? <em key={index}>{part.slice(1, -1)}</em> : <span key={index}>{part}</span>); }
function RichText({ content }: { content: string }) { return <div className="message__content">{content.split("\n").map((line, index) => <p key={`${line}-${index}`}>{renderInline(line)}</p>)}</div>; }
function Actions({ actions, onAction }: { actions: Action[]; onAction: (message: string) => void }) { return <div className="message-actions">{actions.map((action) => <button key={`${action.label}-${action.message}`} type="button" className={action.variant === "primary" ? "primary" : ""} onClick={() => onAction(action.message)}>{action.label}</button>)}</div>; }
function ProgramCard({ program, actions, language, onAction }: { program: ProgramCardType; actions: Action[]; language: Language; onAction: (message: string) => void }) {
  const labels = language === "en" ? { program: "Program", period: "Term", cohort: "Open cohort", deadline: "Deadline", requirements: "Requirements", cost: "Cost", source: "Source", yes: "Yes" } : language === "pt" ? { program: "Programa", period: "Período", cohort: "Turma aberta", deadline: "Data limite", requirements: "Requisitos", cost: "Custo", source: "Fonte", yes: "Sim" } : { program: "Programa", period: "Periodo", cohort: "Cohorte abierta", deadline: "Fecha límite", requirements: "Requisitos", cost: "Costo", source: "Fuente", yes: "Sí" };
  return <article className="program-card"><span className="program-card__status">{program.status}</span><h3>{program.name}</h3><dl><div><dt>{labels.period}</dt><dd>{program.period}</dd></div><div><dt>{labels.cohort}</dt><dd>{labels.yes}</dd></div><div><dt>{labels.deadline}</dt><dd>{program.deadline}</dd></div><div><dt>{labels.requirements}</dt><dd>{program.requirements?.join(" · ")}</dd></div><div><dt>{labels.cost}</dt><dd>{program.costCop ? currency.format(program.costCop) : "—"}</dd></div><div><dt>{labels.source}</dt><dd>{program.source}</dd></div></dl><Actions actions={actions} onAction={onAction} /></article>;
}
export function MessageBubble({ message, language, onAction }: { message: ChatMessage; language: Language; onAction: (message: string) => void }) {
  const assistant = language === "en" ? "Assistant" : language === "pt" ? "Assistente" : "Asistente";
  const you = language === "en" ? "You" : language === "pt" ? "Você" : "Tú";
  return <article className={`message message--${message.role}`}><div className="message__meta">{message.role === "user" ? you : assistant}</div><RichText content={message.content} />{message.ui?.type === "program-card" && <ProgramCard program={message.ui.program} actions={message.ui.actions} language={language} onAction={onAction} />}{message.ui?.type === "actions" && <Actions actions={message.ui.actions} onAction={onAction} />}</article>;
}

