import type { Action, ChatMessage, Language, ProgramCard as ProgramCardType } from "./types";
const currency = new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 });
function renderInline(text: string) { return text.split(/(\*\*[^*]+\*\*|_[^_]+_)/g).filter(Boolean).map((part, index) => part.startsWith("**") && part.endsWith("**") ? <strong key={index}>{part.slice(2, -2)}</strong> : part.startsWith("_") && part.endsWith("_") ? <em key={index}>{part.slice(1, -1)}</em> : <span key={index}>{part}</span>); }
function RichText({ content }: { content: string }) { return <div className="message__content">{content.split("\n").map((line, index) => <p key={`${line}-${index}`}>{renderInline(line)}</p>)}</div>; }
function Actions({ actions, onAction }: { actions: Action[]; onAction: (message: string) => void }) { return <div className="message-actions">{actions.map((action) => <button key={`${action.label}-${action.message}`} type="button" className={action.variant === "primary" ? "primary" : ""} onClick={() => onAction(action.message)}>{action.label}</button>)}</div>; }
function ProgramCard({ program, actions, language, onAction }: { program: ProgramCardType; actions: Action[]; language: Language; onAction: (message: string) => void }) {
  const labels = language === "en" ? { period: "Term", cohort: "Open cohort", deadline: "Deadline", requirements: "Requirements", cost: "Cost", source: "Source", yes: "Yes", apply: "1. Apply", enroll: "2. Enroll", study: "3. Start studying", disclaimer: "Follow these steps to complete your admissions process." } : language === "pt" ? { period: "Período", cohort: "Turma aberta", deadline: "Data limite", requirements: "Requisitos", cost: "Custo", source: "Fonte", yes: "Sim", apply: "1. Candidatura", enroll: "2. Matrícula", study: "3. Início dos estudos", disclaimer: "Siga estas etapas para concluir seu processo de admissão." } : { period: "Periodo", cohort: "Cohorte abierta", deadline: "Fecha límite", requirements: "Requisitos", cost: "Costo", source: "Fuente", yes: "Sí", apply: "1. Postulación", enroll: "2. Registro y matrícula", study: "3. Inicio de estudios", disclaimer: "Sigue estos pasos para completar tu proceso de admisión." };
  const localized = program.id === "systems" && language === "en" ? { name: "Systems Engineering", status: "Admissions open", deadline: "November 30, 2026", requirements: ["Application form", "Admission result", "Academic documents"], applicationSteps: ["Review the program information", "Complete the application form", "Review and submit the information", "Receive the admission result"], enrollmentSteps: ["Accept the place", "Review the tuition", "Open the payment link", "Confirm enrollment"], studyStartSteps: ["Check the academic calendar", "Review the welcome guide", "Select courses", "Start classes on the scheduled date"], source: "Academic program record" } : program.id === "systems" && language === "pt" ? { name: "Engenharia de Sistemas", status: "Inscrições abertas", deadline: "30 de novembro de 2026", requirements: ["Formulário de inscrição", "Resultado de admissão", "Documentos acadêmicos"], applicationSteps: ["Revisar as informações do curso", "Preencher o formulário de inscrição", "Revisar e enviar os dados", "Receber o resultado de admissão"], enrollmentSteps: ["Aceitar a vaga", "Revisar o valor da matrícula", "Abrir o link de pagamento", "Confirmar a matrícula"], studyStartSteps: ["Consultar o calendário acadêmico", "Revisar o guia de boas-vindas", "Selecionar disciplinas", "Iniciar as aulas na data programada"], source: "Ficha acadêmica do curso" } : { name: program.name, status: program.status, deadline: program.deadline, requirements: program.requirements, applicationSteps: program.applicationSteps, enrollmentSteps: program.enrollmentSteps, studyStartSteps: program.studyStartSteps, source: program.source };
  return <article className="program-card"><span className="program-card__status">{localized.status}</span><h3>{localized.name}</h3><dl><div><dt>{labels.period}</dt><dd>{program.period}</dd></div><div><dt>{labels.cohort}</dt><dd>{labels.yes}</dd></div><div><dt>{labels.deadline}</dt><dd>{localized.deadline}</dd></div><div><dt>{labels.requirements}</dt><dd>{localized.requirements?.join(" · ")}</dd></div><div><dt>{labels.cost}</dt><dd>{program.costCop ? currency.format(program.costCop) : "—"}</dd></div><div><dt>{labels.source}</dt><dd>{localized.source}</dd></div></dl>{localized.applicationSteps && <div className="program-steps"><p>{labels.disclaimer}</p><StepList title={labels.apply} steps={localized.applicationSteps} /><StepList title={labels.enroll} steps={localized.enrollmentSteps ?? []} /><StepList title={labels.study} steps={localized.studyStartSteps ?? []} /></div>}<Actions actions={actions} onAction={onAction} /></article>;
}
function StepList({ title, steps }: { title: string; steps: string[] }) { return <section><h4>{title}</h4><ol>{steps.map((step) => <li key={step}>{step}</li>)}</ol></section>; }
export function MessageBubble({ message, language, onAction }: { message: ChatMessage; language: Language; onAction: (message: string) => void }) {
  const assistant = language === "en" ? "Assistant" : language === "pt" ? "Assistente" : "Asistente";
  const you = language === "en" ? "You" : language === "pt" ? "Você" : "Tú";
  return <article className={`message message--${message.role}`}><div className="message__meta">{message.role === "user" ? you : assistant}</div><RichText content={message.content} />{message.ui?.type === "program-card" && <ProgramCard program={message.ui.program} actions={message.ui.actions} language={language} onAction={onAction} />}{message.ui?.type === "actions" && <Actions actions={message.ui.actions} onAction={onAction} />}</article>;
}
